### ISSUE TITLE
lndp link does not work with html textbox submit

### ISSUE THREAD

**Issue by okofishe** [ndrsf/log4shell#1]
Hello,
Having study your code carefully, even though it works perfectly with curl header User Agent request, it will not work when submitting to an html input box submit. The class is only reference but not executed.

Any thought about that....

**Comment by ndrsf** [comment]
Hi,
can you elaborate what "class is only referenced" means? Are you sure the User-Agent header is sent correctly? Maybe use Wireshark to debug the exact payload sent to the server.
